name: Prepare Translations For NPM
description: Prepares translations for NPM publishing, ensuring that new lang terms have temporary English translations
inputs:
  LANG_PATH:
    description: Path to your repo's translation files
    required: true
runs:
  using: composite
  steps:
    - name: Installing chalk
      run: npm install --prefix ${{ github.action_path }} chalk@4
      shell: bash
    - name: Preparing translations
      run: node ${{ github.action_path }}/prepare-translations.js
      env:
        LANG_PATH: ${{ github.workspace }}/${{ inputs.LANG_PATH }}
        FORCE_COLOR: 3
      shell: bash
